version: 2.1

jobs:
  publish-release:
    parameters:
      tag:
        type: string
        description: What git tag to use when tagging remote repository
    docker:
      - image: cimg/base:2022.07
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Publish to npmjs
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm config set scope fluxninja --global
            npm ci
            npm publish --access public

workflows:
  version: 2

  publish-release:
    when:
      matches:
        { value: << pipeline.git.tag >>, pattern: "^releases/.*$" }
    jobs:
      - publish-release:
          context: npmjs
          # both this and workflow's when is needed
          filters:
            branches:
              ignore: /.+/
            tags:
              only: /^releases\/.*$/
